CREATE TABLE [dbo].[PackageStatistics](
	[Name] [nvarchar](400) NOT NULL,
	[Count] [int] NOT NULL,
	[LatestSupportType] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_PackageStatistics] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
