using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using FluentAssertions;
using ICanHasDotnetCore.NugetPackages;
using NuGet.Versioning;
using Xunit;

namespace ICanHasDotnetCore.Tests.Magic.NugetPackages
{
    [SuppressMessage("ReSharper", "VSTHRD200")]
    public abstract class WholeStackOfPackagesTests
    {
        public const int DegreeOfParallelism = 4;

        public static List<object[]> Packages = new List<object[]>
        {
            new object[] {"51Degrees.mobi-webMatrix", "3.2.10.3-beta", SupportType.Unsupported},
            new object[] {"ABCpdf", "10.1.1.1", SupportType.Unsupported},
            new object[] {"Abot", "1.5.1.42", SupportType.Unsupported},
            new object[] {"Abp", "0.10.1.2", SupportType.Unsupported},
            new object[] {"Abp.AutoMapper", "0.10.1.0", SupportType.Unsupported},
            new object[] {"Abp.EntityFramework", "0.10.1.0", SupportType.Unsupported},
            new object[] {"Abp.EntityFramework.Common", "0.10.1.0", SupportType.Unsupported},
            new object[] {"Akka", "1.1.1", SupportType.Unsupported},
            new object[] {"Akka.Cluster", "1.1.1", SupportType.Unsupported},
            new object[] {"AndroidSegmentedControl.Droid.Binding", "1.0.2", SupportType.Unsupported},
            new object[] {"AngleSharp", "0.9.7", SupportType.Supported},
            new object[] {"Angular.UI.Bootstrap", "1.3.3", SupportType.NoDotNetLibraries},
            new object[] {"Angular.UI.UI-Router", "0.2.18", SupportType.NoDotNetLibraries},
            new object[] {"Angular.UI.Utils", "0.2.3", SupportType.NoDotNetLibraries},
            new object[] {"angular-file-upload", "12.0.4", SupportType.NoDotNetLibraries},
            new object[] {"AngularGoogleMaps", "2.0.1", SupportType.Unsupported},
            new object[] {"AngularInjector", "1.0.0", SupportType.Unsupported},
            new object[] {"angularjs", "1.5.7", SupportType.NoDotNetLibraries},
            new object[] {"AngularJS.Animate", "1.5.7", SupportType.NoDotNetLibraries},
            new object[] {"Aspose.Words", "16.6.0", SupportType.Unsupported},
            new object[] {"AsyncErrorHandler.Fody", "1.0.11.0", SupportType.NoDotNetLibraries},
            new object[] {"AsyncIO", "0.1.26.0", SupportType.Supported},
            new object[] {"AttributeRouting", "3.5.6", SupportType.NotFound},
            new object[] {"Autofac.Web", "4.0.0", SupportType.Unsupported},
            new object[] {"DotNetOpenAuth.OAuth.Consumer", "5.0.0-alpha3", SupportType.Unsupported},
            new object[] {"EnterpriseLibrary.TransientFaultHandling.Configuration", "6.0.1304.0", SupportType.Unsupported},
            new object[] {"FSharp.Data", "2.3.1", SupportType.Supported},
            new object[] {"FSharp.Data.TypeProviders", "5.0.0.2", SupportType.Unsupported},
            new object[] {"Glimpse", "2.0.0-beta1", SupportType.PreRelease},
            new object[] {"glue", "0.9", SupportType.Unsupported},
            new object[] {"Google.Apis", "1.14.0", SupportType.Unsupported},
            new object[] {"Google.Apis.Admin.Directory.directory_v1", "1.14.0.561", SupportType.Supported},
            new object[] {"Google.Apis.AndroidPublisher.v2", "1.14.0.543", SupportType.Supported},
            new object[] {"Google.Apis.Auth", "1.14.0", SupportType.Unsupported},
            new object[] {"Google.Apis.Calendar.v3", "1.14.0.558", SupportType.Supported},
            new object[] {"Google.Apis.Core", "1.14.0", SupportType.Unsupported},
            new object[] {"Google.Apis.Customsearch.v1", "1.14.0.466", SupportType.Supported},
            new object[] {"Google.GData.Client", "2.2.0.0", SupportType.Unsupported},
            new object[] {"Google.GData.Extensions", "2.2.0.0", SupportType.Unsupported},
            new object[] {"Google.ProtocolBuffers", "2.4.1.555", SupportType.Unsupported},
            new object[] {"googlemaps.TypeScript.DefinitelyTyped", "0.7.1", SupportType.NoDotNetLibraries},
            new object[] {"GraphicsMagick.NET-Q16-AnyCPU", "1.3.23.1", SupportType.Unsupported},
            new object[] {"GraphViz.NET", "1.0.0", SupportType.Unsupported},
            new object[] {"GravatarHelper", "3.3.2", SupportType.Unsupported},
            new object[] {"Grid.Mvc", "3.1.0-ci1036", SupportType.Unsupported},
            new object[] {"Grid.Mvc.DatePicker", "1.0.0", SupportType.NoDotNetLibraries},
            new object[] {"Grid.Mvc.Redux", "1.0.4", SupportType.Unsupported},
            new object[] {"Griddly", "1.5.7.0", SupportType.NoDotNetLibraries},
            new object[] {"Halibut", "2.2.3", SupportType.Unsupported},
            new object[] {"Hammock", "1.3.1", SupportType.Unsupported},
            new object[] {"handlebars.TypeScript.DefinitelyTyped", "1.1.7", SupportType.NoDotNetLibraries},
            new object[] {"Hangfire", "1.6.0", SupportType.Supported},
            new object[] {"Hangfire.AspNetCore", "1.6.0", SupportType.Supported},
            new object[] {"Hangfire.Autofac", "2.2.0", SupportType.Unsupported},
            new object[] {"Hangfire.Core", "1.6.0", SupportType.Supported},
            new object[] {"Hangfire.Dashboard.Authorization", "2.1.0", SupportType.Unsupported},
            new object[] {"Hangfire.MemoryStorage", "1.3.0.0", SupportType.Unsupported},
            new object[] {"Hangfire.Ninject", "1.2.0", SupportType.Unsupported},
            new object[] {"Hangfire.SimpleInjector", "1.3.0.0", SupportType.Unsupported},
            new object[] {"Hangfire.SqlServer", "1.6.0", SupportType.Supported},
            new object[] {"Hangfire.StructureMap", "1.6.0", SupportType.Unsupported},
            new object[] {"Harvest.Chosen", "1.4.2", SupportType.NoDotNetLibraries},
            new object[] {"Heijden.Dns", "1.0.0", SupportType.Unsupported},
            new object[] {"Hekate", "3.2.0", SupportType.Supported},
            new object[] {"Helios", "2.1.2", SupportType.Unsupported},
            new object[] {"highcharts.TypeScript.DefinitelyTyped", "0.4.3", SupportType.NoDotNetLibraries},
            new object[] {"history.TypeScript.DefinitelyTyped", "0.2.7", SupportType.NoDotNetLibraries},
            new object[] {"Hopac", "0.2.1", SupportType.Unsupported},
            new object[] {"html5shiv", "0.1.0.8", SupportType.NoDotNetLibraries},
            new object[] {"HtmlAgilityPack", "1.4.9.5", SupportType.Supported},
            new object[] {"HtmlAgilityPack.NetCore", "1.4.9.2", SupportType.Supported},
            new object[] {"HtmlSanitizationLibrary", "1.0.0", SupportType.Unsupported},
            new object[] {"HtmlSanitizer", "3.3.127-beta", SupportType.PreRelease},
            new object[] {"Http.fs-prerelease", "3.0.5", SupportType.NotFound},
            new object[] {"HttpClientDiagnostics", "1.1.1.1462518862", SupportType.Unsupported},
            new object[] {"Humanizer", "2.1.0", SupportType.NoDotNetLibraries},
            new object[] {"Humanizer.Core", "2.1.0", SupportType.Supported},
            new object[] {"Humanizer.Core.af", "2.1.0", SupportType.Supported},
            new object[] {"Humanizer.Core.de", "2.1.0", SupportType.Supported},
            new object[] {"Hyak.Common", "1.1.0", SupportType.Unsupported},
            new object[] {"ICSharpCode.SharpZipLib.dll", "0.85.4.369", SupportType.Unsupported},
            new object[] {"IdentityModel", "2.0.0-beta5", SupportType.PreRelease},
            new object[] {"IdentityServer.WindowsAuthentication", "1.1.1", SupportType.Unsupported},
            new object[] {"IdentityServer3", "2.5.1", SupportType.Unsupported},
            new object[] {"IdentityServer3.AccessTokenValidation", "2.10.0", SupportType.Unsupported},
            new object[] {"IdentityServer3.AspNetIdentity", "2.0.0", SupportType.NoDotNetLibraries},
            new object[] {"IdentityServer3.MembershipReboot", "2.0.0", SupportType.NoDotNetLibraries},
            new object[] {"Iesi.Collections", "4.0.1.4000", SupportType.Unsupported},
            new object[] {"IKVM", "8.1.5717.0", SupportType.Unsupported},
            new object[] {"ILRepack", "2.1.0-beta1", SupportType.NoDotNetLibraries},
            new object[] {"ImageProcessor", "2.4.3.0", SupportType.Unsupported},
            new object[] {"ImageProcessor.Web", "4.6.3.0", SupportType.Unsupported},
            new object[] {"ImageProcessor.Web.Config", "2.3.0.0", SupportType.NoDotNetLibraries},
            new object[] {"ImageResizer", "4.0.5", SupportType.Unsupported},
            new object[] {"ImageResizer.Mvc", "4.0.5", SupportType.NoDotNetLibraries},
            new object[] {"ImageResizer.MvcWebConfig", "4.0.5", SupportType.NoDotNetLibraries},
            new object[] {"ImageResizer.Plugins.AzureReader2", "4.0.5", SupportType.Unsupported},
            new object[] {"ImageResizer.Plugins.DiskCache", "4.0.5", SupportType.Unsupported},
            new object[] {"ImageResizer.Plugins.SqlReader", "4.0.5", SupportType.Unsupported},
            new object[] {"ImageResizer.WebConfig", "4.0.5", SupportType.NoDotNetLibraries},
            new object[] {"ImpromptuInterface", "6.2.2", SupportType.Unsupported},
            new object[] {"InstaSharp", "2.0.4", SupportType.Unsupported},
            new object[] {"IPAddressRange", "1.6.0.0", SupportType.Unsupported},
            new object[] {"IppDotNetSdkForQuickBooksApiV3", "2.5.0", SupportType.NotFound},
            new object[] {"iTextSharp", "5.5.9", SupportType.Unsupported},
            new object[] {"itextsharp.pdfa", "5.5.9", SupportType.Unsupported},
            new object[] {"itextsharp.xmlworker", "5.5.9", SupportType.Unsupported},
            new object[] {"Janitor.Fody", "1.2.1.0", SupportType.Supported},
            new object[] {"jasmine.TypeScript.DefinitelyTyped", "2.3.2", SupportType.NoDotNetLibraries},
            new object[] {"JavaScriptEngineSwitcher.Core", "1.5.0", SupportType.Unsupported},
            new object[] {"JavaScriptEngineSwitcher.Msie", "1.5.4", SupportType.Unsupported},
            new object[] {"JavaScriptEngineSwitcher.V8", "1.5.8", SupportType.Unsupported},
            new object[] {"JetBrains.Annotations", "10.1.5", SupportType.Supported},
            new object[] {"JetBrains.Annotations.Core", "8.2.0.2160", SupportType.Unsupported},
            new object[] {"Jil", "2.14.3", SupportType.Unsupported},
            new object[] {"Jint", "2.8", SupportType.Unsupported},
            new object[] {"jose-jwt", "1.9.3", SupportType.Unsupported},
            new object[] {"jQuery", "3.1.0", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.Ajax.Unobtrusive", "2.0.20710.0", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.ba-throttle-debounce", "1.1.0", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.BlockUI", "2.70", SupportType.NoDotNetLibraries},
            new object[] {"jquery.datatables", "1.10.11", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.Easing", "1.3.0.1", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.Migrate", "3.0.0", SupportType.NoDotNetLibraries},
            new object[] {"jquery.TypeScript.DefinitelyTyped", "3.1.0", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.UI.Combined", "1.12.0", SupportType.NoDotNetLibraries},
            new object[] {"jquery.validate.unobtrusive.bootstrap", "1.2.3", SupportType.NoDotNetLibraries},
            new object[] {"jQuery.Validation", "1.15.0", SupportType.NoDotNetLibraries},
            new object[] {"jquery-globalize", "1.1.1", SupportType.NoDotNetLibraries},
            new object[] {"jquery-timepicker-jt", "1.9.0", SupportType.NoDotNetLibraries},
            new object[] {"json2", "1.0.2", SupportType.NoDotNetLibraries},
            new object[] {"JSPool", "0.4.1", SupportType.Unsupported},
            new object[] {"JWT", "1.3.4", SupportType.Unsupported},
            new object[] {"Knockout.Mapping", "2.4.0", SupportType.NoDotNetLibraries},
            new object[] {"Knockout.Validation", "2.0.3", SupportType.NoDotNetLibraries},
            new object[] {"knockoutjs", "3.4.0", SupportType.NoDotNetLibraries},
            new object[] {"libphonenumber-csharp", "7.2.5", SupportType.Unsupported},
            new object[] {"LibSassHost", "0.5.2", SupportType.Unsupported},
            new object[] {"Libuv", "1.9.0", SupportType.Supported},
            new object[] {"LightInject", "4.0.11", SupportType.Supported},
            new object[] {"LightningDB", "0.9.4", SupportType.Supported},
            new object[] {"LinqKit", "1.1.7.0", SupportType.Supported},
            new object[] {"LinqToQuerystring", "0.7.0.8", SupportType.Unsupported},
            new object[] {"LoadAssembliesOnStartup.Fody", "1.7.0", SupportType.NoDotNetLibraries},
            new object[] {"lodash", "4.13.1", SupportType.NoDotNetLibraries},
            new object[] {"log4net", "2.0.5", SupportType.Unsupported},
            new object[] {"log4net.Raygun.WebApi", "4.2.0.18163", SupportType.Unsupported},
            new object[] {"logentries.core", "2.8.0", SupportType.Unsupported},
            new object[] {"logentries.log4net", "2.8.0", SupportType.Unsupported},
            new object[] {"logentries.nlog", "2.6.0", SupportType.Unsupported},
            new object[] {"loggly-csharp", "4.5.1.11", SupportType.Unsupported},
            new object[] {"loggly-csharp-config", "4.5.1.11", SupportType.Unsupported},
            new object[] {"Lu.AspnetIdentity.Dapper", "0.0.3.3", SupportType.Unsupported},
            new object[] {"Lucene.Net", "3.0.3", SupportType.Unsupported},
            new object[] {"Magnum", "2.1.3", SupportType.Unsupported},
            new object[] {"MahApps.Metro", "1.3.0-ALPHA178", SupportType.NotFound},
            new object[] {"MailChimp.NET", "1.1.88", SupportType.Unsupported},
            new object[] {"MailKit", "1.16.1", SupportType.Supported},
            new object[] {"Markdown", "1.14.7", SupportType.Supported},
            new object[] {"MarkdownSharp", "1.13.0.0", SupportType.Unsupported},
            new object[] {"Marten", "1.0.0-alpha-625", SupportType.PreRelease},
            new object[] {"MassTransit", "3.3.5", SupportType.NotFound},
            new object[] {"MassTransit.RabbitMQ", "3.3.5", SupportType.NotFound},
            new object[] {"MaterialDesignColors", "1.1.3", SupportType.Unsupported},
            new object[] {"MaterialDesignThemes", "2.0.1-ci644", SupportType.Unsupported},
            new object[] {"MaterialDesignThemes.MahApps", "0.0.6", SupportType.Unsupported},
            new object[] {"MathNet.Numerics", "3.12.0", SupportType.Supported},
            new object[] {"MaxMind.Db", "2.1.1-beta1", SupportType.PreRelease},
            new object[] {"MaxMind.GeoIP2", "2.7.0-beta2", SupportType.PreRelease},
            new object[] {"MediatR", "2.1.0", SupportType.Supported},
            new object[] {"MediaTypeMap", "2.1.0.0", SupportType.Unsupported},
            new object[] {"Metrics.NET", "0.4.0-pre", SupportType.Unsupported},
            new object[] {"MicosoftReportViewerWebForms_v11", "1.0.1", SupportType.Unsupported},
            new object[] {"MicroBuild.Core", "0.2.0", SupportType.NotFound},
            new object[] {"Microsoft.AnalyzerPowerPack", "1.1.0", SupportType.NotFound},
            new object[] {"Microsoft.ApplicationInsights", "2.2.0-beta1", SupportType.PreRelease},
            new object[] {"Microsoft.ApplicationInsights.Agent.Intercept", "2.0.1", SupportType.Unsupported},
            new object[] {"Microsoft.ApplicationInsights.AspNetCore", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.ApplicationInsights.DependencyCollector", "2.2.0-beta1", SupportType.Unsupported},
            new object[] {"Microsoft.ApplicationInsights.Log4NetAppender", "2.1.0", SupportType.Unsupported},
            new object[] {"Microsoft.ApplicationInsights.NLogTarget", "2.1.0", SupportType.Unsupported},
            new object[] {"Microsoft.ApplicationInsights.TraceListener", "2.1.0", SupportType.Unsupported},
            new object[] {"Microsoft.ApplicationInsights.Web", "2.2.0-beta1", SupportType.Unsupported},
            new object[] {"Microsoft.AspNetCore.Antiforgery", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.AspNetCore.Authentication", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.AspNetCore.Authentication.Cookies", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.AspNetCore.Authentication.OpenIdConnect", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.AspNetCore.Authorization", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.AspNetCore.Cors", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.Azure.DocumentDB", "1.9.1", SupportType.NotFound},
            new object[] {"Microsoft.Azure.KeyVault.Core", "1.0.0", SupportType.Supported},
            new object[] {"Microsoft.Azure.NotificationHubs", "1.0.6", SupportType.Unsupported},
            new object[] {"Microsoft.Azure.Search", "1.1.2", SupportType.Unsupported},
            new object[] {"Microsoft.Extensions.Logging.Debug", "1.0.0", SupportType.Supported},
            new object[] {"MimeKit", "1.4.1", SupportType.NotFound},
            new object[] {"Mindscape.Raygun4Net", "5.3.1", SupportType.Unsupported},
            new object[] {"Nancy", "2.0.0-barneyrubble", SupportType.PreRelease},
            new object[] {"Ninject", "3.2.3-unstable-012", SupportType.Unsupported},
            new object[] {"NuGet.LibraryModel", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.PackageNPublish", "0.8.0.2", SupportType.NoDotNetLibraries},
            new object[] {"NuGet.Packaging", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.Packaging.Core", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.Packaging.Core.Types", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.ProjectModel", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.Protocol.Core.Types", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.Protocol.Core.v3", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.Repositories", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.RuntimeModel", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NuGet.Versioning", "3.5.0-beta2-1484", SupportType.PreRelease},
            new object[] {"NUnit", "3.4.1", SupportType.Supported},
            new object[] {"NUnit.Console", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.ConsoleRunner", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.Extension.NUnitProjectLoader", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.Extension.NUnitV2Driver", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.Extension.NUnitV2ResultWriter", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.Extension.TeamCityEventListener", "1.0.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.Extension.VSProjectLoader", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit.Runners", "3.4.1", SupportType.NoDotNetLibraries},
            new object[] {"NUnit3TestAdapter", "3.4.0", SupportType.Unsupported},
            new object[] {"NUnitLite", "3.4.1", SupportType.Supported},
            new object[] {"NUnitTestAdapter", "2.0.0", SupportType.Unsupported},
            new object[] {"nuPickers", "1.5.3", SupportType.Unsupported},
            new object[] {"Nustache", "1.16.0.1", SupportType.Unsupported},
            new object[] {"OAuth2", "0.8.37", SupportType.Unsupported},
            new object[] {"Octokit", "0.20.0", SupportType.Supported},
            new object[] {"OctoPack", "3.0.71", SupportType.NoDotNetLibraries},
            new object[] {"Octopus.Client", "3.4.0-beta0002", SupportType.Unsupported},
            new object[] {"Octostache", "1.0.2.40", SupportType.Unsupported},
            new object[] {"Oracle.ManagedDataAccess", "12.1.24160419", SupportType.Unsupported},
            new object[] {"Our.Umbraco.CoreValueConverters", "3.0.0", SupportType.Unsupported},
            new object[] {"Our.Umbraco.NestedContent", "0.3.0", SupportType.Unsupported},
            new object[] {"OwinRequestScopeContext", "1.0.1", SupportType.Unsupported},
            new object[] {"PagedList", "1.17.0.0", SupportType.Unsupported},
            new object[] {"PagedList.Mvc", "4.5.0.0", SupportType.Unsupported},
            new object[] {"PCLCrypto", "2.0.147", SupportType.Supported},
            new object[] {"PCLStorage", "1.0.2", SupportType.Supported},
            new object[] {"PDFsharp-MigraDoc-gdi", "1.50.4000-beta3b", SupportType.Unsupported},
            new object[] {"PhantomJS", "2.1.1", SupportType.NoDotNetLibraries},
            new object[] {"PInvoke.BCrypt", "0.3.2", SupportType.Supported},
            new object[] {"PInvoke.Kernel32", "0.3.2", SupportType.Supported},
            new object[] {"PInvoke.NCrypt", "0.3.2", SupportType.Supported},
            new object[] {"PInvoke.Windows.Core", "0.3.2", SupportType.Supported},
            new object[] {"Platform.NET", "1.2.1.283", SupportType.Unsupported},
            new object[] {"Platform.Xml.Serialization", "1.2.1.283", SupportType.Unsupported},
            new object[] {"Polly", "4.3.0", SupportType.Supported},
            new object[] {"Portable.BouncyCastle", "1.8.1.1", SupportType.Supported},
            new object[] {"Portable.Licensing", "1.1.0", SupportType.Unsupported},
            new object[] {"PortableRest.Signed", "3.1.0-Beta4", SupportType.PreRelease},
            new object[] {"Postal.Mvc5", "1.2.0", SupportType.Unsupported},
            new object[] {"PostSharp", "4.3.13-rc", SupportType.Unsupported},
            new object[] {"Prism.Core", "6.2.0-pre1", SupportType.Unsupported},
            new object[] {"Prism.Wpf", "6.1.1-pre2", SupportType.Unsupported},
            new object[] {"PropertyChanged.Fody", "1.51.3", SupportType.Supported},
            new object[] {"protobuf-net", "2.1.0", SupportType.Supported},
            new object[] {"PubSub", "1.5.0", SupportType.Unsupported},
            new object[] {"Punchclock", "1.2.0", SupportType.Supported},
            new object[] {"Q", "2.0.2-experimental", SupportType.NoDotNetLibraries},
            new object[] {"Quartz", "2.3.3", SupportType.Unsupported},
            new object[] {"RabbitMQ.Client", "3.6.3", SupportType.Unsupported},
            new object[] {"RavenDB.Client", "3.0.30172-Hotfix", SupportType.Unsupported},
            new object[] {"RavenDB.Client.Authorization", "3.0.30172-Hotfix", SupportType.Unsupported},
            new object[] {"RazorEngine", "4.4.0-rc1", SupportType.Unsupported},
            new object[] {"RazorGenerator.MsBuild", "2.4.5", SupportType.NoDotNetLibraries},
            new object[] {"RazorGenerator.Mvc", "2.4.2", SupportType.Unsupported},
            new object[] {"React.Core", "2.5.0", SupportType.Unsupported},
            new object[] {"react.js", "0.14.7", SupportType.NoDotNetLibraries},
            new object[] {"React.Web", "2.5.0", SupportType.Unsupported},
            new object[] {"React.Web.Mvc4", "2.5.0", SupportType.Unsupported},
            new object[] {"reactiveui", "6.5.0", SupportType.NotFound},
            new object[] {"ReactiveUI.Fody", "1.1.51", SupportType.Supported},
            new object[] {"reactiveui-androidsupport", "6.5.0", SupportType.NotFound},
            new object[] {"reactiveui-core", "6.5.0", SupportType.NotFound},
            new object[] {"reactiveui-events", "6.5.0", SupportType.NotFound},
            new object[] {"recaptcha", "1.0.5.0", SupportType.Unsupported},
            new object[] {"RecaptchaNet", "2.1.0", SupportType.Unsupported},
            new object[] {"RedisAspNetProviders", "1.0.1", SupportType.Unsupported},
            new object[] {"RefactorThis.GraphDiff", "2.0.1", SupportType.Unsupported},
            new object[] {"refit", "2.4.1", SupportType.Supported},
            new object[] {"Remotion.Linq", "2.1.1", SupportType.Supported},
            new object[] {"ReportViewerCommon", "11.0.0.0", SupportType.Unsupported},
            new object[] {"RequireJS", "2.2.0", SupportType.NoDotNetLibraries},
            new object[] {"requirejs.TypeScript.DefinitelyTyped", "0.4.3", SupportType.NoDotNetLibraries},
            new object[] {"ReSharper.Annotations", "7.1.3.130415", SupportType.Unsupported},
            new object[] {"Respond", "1.4.2", SupportType.NoDotNetLibraries},
            new object[] {"RestSharp", "105.2.3", SupportType.Unsupported},
            new object[] {"RhinoMocks", "4.0.0-alpha3", SupportType.Unsupported},
            new object[] {"RJP.UmbracoMultiUrlPicker", "1.3.1", SupportType.Unsupported},
            new object[] {"RollbarSharp", "1.0.0.0", SupportType.Unsupported},
            new object[] {"Rotativa", "1.7.1-beta", SupportType.Unsupported},
            new object[] {"routedebugger", "2.1.5", SupportType.Unsupported},
            new object[] {"Rssdp", "1.0.0.12", SupportType.Supported},
            new object[] {"runtime.native.System", "4.0.0", SupportType.Supported},
            new object[] {"runtime.native.System.Net.Http", "4.0.1", SupportType.Supported},
            new object[] {"runtime.native.System.Security.Cryptography", "4.0.0", SupportType.Supported},
            new object[] {"Ruzzie.Common", "0.6.26", SupportType.Unsupported},
            new object[] {"Sammy.js", "0.7.5", SupportType.NoDotNetLibraries},
            new object[] {"Select2.js", "4.0.3", SupportType.NoDotNetLibraries},
            new object[] {"Selenium.Support", "2.53.1", SupportType.Unsupported},
            new object[] {"Selenium.WebDriver", "2.53.1", SupportType.Unsupported},
            new object[] {"Selenium.WebDriver.ChromeDriver", "2.22.0.0", SupportType.NoDotNetLibraries},
            new object[] {"semver", "1.1.2", SupportType.Unsupported},
            new object[] {"Sendgrid", "7.1.1", SupportType.Unsupported},
            new object[] {"SendGrid.CSharp.HTTP.Client", "2.0.7", SupportType.Unsupported},
            new object[] {"SendGrid.SmtpApi", "1.3.1", SupportType.Unsupported},
            new object[] {"Seq.Client.NLog", "2.3.14", SupportType.Unsupported},
            new object[] {"Serilog", "2.1.0-dev-00670", SupportType.PreRelease},
            new object[] {"Serilog.Enrichers.Thread", "2.0.0", SupportType.Supported},
            new object[] {"Serilog.Extensions.Logging", "1.1.0-dev-10116", SupportType.PreRelease},
            new object[] {"Serilog.Extras.MSOwin", "2.0.1", SupportType.NoDotNetLibraries},
            new object[] {"Serilog.Extras.Timing", "2.0.2", SupportType.NoDotNetLibraries},
            new object[] {"Serilog.Extras.Topshelf", "2.0", SupportType.NoDotNetLibraries},
            new object[] {"Serilog.Settings.AppSettings", "2.0.0", SupportType.Unsupported},
            new object[] {"Serilog.Sinks.Elasticsearch", "4.0.142", SupportType.Unsupported},
            new object[] {"Serilog.Sinks.File", "2.1.0", SupportType.Supported},
            new object[] {"Serilog.Sinks.Literate", "2.1.0-dev-00028", SupportType.PreRelease},
            new object[] {"Serilog.Sinks.MSSqlServer", "4.0.0", SupportType.Unsupported},
            new object[] {"Serilog.Sinks.PeriodicBatching", "2.0.0", SupportType.Supported},
            new object[] {"Serilog.Sinks.RollingFile", "2.1.0", SupportType.Supported},
            new object[] {"Serilog.Sinks.Seq", "3.0.0-dev-00069", SupportType.PreRelease},
            new object[] {"Serilog.Sinks.Stackify", "1.23.1-beta2", SupportType.PreRelease},
            new object[] {"Serilog.Sinks.Trace", "2.0.0", SupportType.Supported},
            new object[] {"SerilogMetrics", "1.0.34", SupportType.Unsupported},
            new object[] {"SerilogWeb.Classic", "2.0.9", SupportType.Unsupported},
            new object[] {"SerilogWeb.Owin", "1.0.1", SupportType.Unsupported},
            new object[] {"ServerAppFabric.Client", "1.1.2106.32", SupportType.Unsupported},
            new object[] {"ServiceStack", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Api.Swagger", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Client", "4.0.60", SupportType.Supported},
            new object[] {"ServiceStack.Common", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Interfaces", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Logging.Elmah", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Logging.NLog", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.OrmLite", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.OrmLite.SqlServer", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Redis", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Server", "4.0.60", SupportType.Unsupported},
            new object[] {"ServiceStack.Text", "4.0.60", SupportType.Supported},
            new object[] {"SevenZipSharp", "0.64", SupportType.NotFound},
            new object[] {"Shaolinq", "1.1.0.924", SupportType.Unsupported},
            new object[] {"Shaolinq.Sqlite", "1.1.0.924", SupportType.Unsupported},
            new object[] {"Shaolinq.SqlServer", "1.1.0.924", SupportType.Unsupported},
            new object[] {"SharpBITS", "2.1.0", SupportType.Unsupported},
            new object[] {"SharpSerializer", "2.20", SupportType.Unsupported},
            new object[] {"SharpZipLib", "0.86.0", SupportType.Unsupported},
            new object[] {"Shouldly", "2.8.0", SupportType.Supported},
            new object[] {"Sigil", "4.7.0", SupportType.Supported},
            new object[] {"signalr.TypeScript.DefinitelyTyped", "0.4.1", SupportType.NoDotNetLibraries},
            new object[] {"SimpleInjector", "3.2.0", SupportType.Supported},
            new object[] {"SimpleInjector.Extensions.ExecutionContextScoping", "3.2.0", SupportType.Supported},
            new object[] {"SimpleInjector.Extensions.LifetimeScoping", "3.2.0", SupportType.Supported},
            new object[] {"SimpleInjector.Integration.Web", "3.2.0", SupportType.Unsupported},
            new object[] {"SimpleInjector.Integration.Web.Mvc", "3.2.0", SupportType.Unsupported},
            new object[] {"SimpleInjector.Integration.WebApi", "3.2.0", SupportType.Unsupported},
            new object[] {"SimpleInjector.Integration.WebApi.WebHost.QuickStart", "3.2.0", SupportType.NoDotNetLibraries},
            new object[] {"SimpleInjector.Packaging", "3.2.0", SupportType.Supported},
            new object[] {"SimpleJson", "0.38.0", SupportType.NoDotNetLibraries},
            new object[] {"SlowCheetah", "2.5.15", SupportType.NoDotNetLibraries},
            new object[] {"Soda.GoogleAnalytics", "1.0.4491.30130", SupportType.Unsupported},
            new object[] {"Soda.GoogleAnalytics.MVC", "1.0.4491.29854", SupportType.Unsupported},
            new object[] {"SonarAnalyzer.CSharp", "1.15.0", SupportType.NoDotNetLibraries},
            new object[] {"SourceLink.Fake", "1.1.0", SupportType.NoDotNetLibraries},
            new object[] {"Spin.js", "2.3.2.1", SupportType.NoDotNetLibraries},
            new object[] {"Splat", "1.6.2", SupportType.Supported},
            new object[] {"Sprache", "2.0.0.52", SupportType.Unsupported},
            new object[] {"sqlite-net-pcl", "1.1.2", SupportType.Supported},
            new object[] {"structuremap", "4.2.0.402", SupportType.Supported},
            new object[] {"WebGrease", "1.6.0", SupportType.Unsupported},
            new object[] {"WebMarkupMin.Core", "2.1.0", SupportType.Supported},
            new object[] {"Wire", "0.7.1", SupportType.Supported},
            new object[] {"Xunit", "2.2.0-beta2-build3300", SupportType.NoDotNetLibraries},
            new object[] {"Zlib.Portable", "1.11.0", SupportType.Unsupported}
        };

        private readonly NugetPackageInfoRetriever _nugetPackageInfoRetriever;

        protected WholeStackOfPackagesTests()
        {
            _nugetPackageInfoRetriever = new NugetPackageInfoRetriever(new PackageRepositoryWrapper(logger: null), new NoNugetResultCache());
        }

        public async Task<NugetPackage> GetPackageAsync(string id, string version)
        {
            return await _nugetPackageInfoRetriever.Retrieve(id, NuGetVersion.Parse(version));
        }
    }

    [SuppressMessage("ReSharper", "VSTHRD200")]
    public class WholeStackOfPackagesTests1 : WholeStackOfPackagesTests
    {
        public new static IEnumerable<object[]> Packages = WholeStackOfPackagesTests.Packages.Where((data, index) => index % DegreeOfParallelism == 0);

        [Theory]
        [MemberData(nameof(Packages))]
        public async Task CheckTheSupportTypeOfAWholeStackOfPackages(string id, string version, SupportType expectedSupportType)
        {
            var package = await GetPackageAsync(id, version);
            package.SupportType.Should().Be(expectedSupportType);
        }
    }

    [SuppressMessage("ReSharper", "VSTHRD200")]
    public class WholeStackOfPackagesTests2 : WholeStackOfPackagesTests
    {
        public new static IEnumerable<object[]> Packages = WholeStackOfPackagesTests.Packages.Where((data, index) => index % DegreeOfParallelism == 1);

        [Theory]
        [MemberData(nameof(Packages))]
        public async Task CheckTheSupportTypeOfAWholeStackOfPackages(string id, string version, SupportType expectedSupportType)
        {
            var package = await GetPackageAsync(id, version);
            package.SupportType.Should().Be(expectedSupportType);
        }
    }

    [SuppressMessage("ReSharper", "VSTHRD200")]
    public class WholeStackOfPackagesTests3 : WholeStackOfPackagesTests
    {
        public new static IEnumerable<object[]> Packages = WholeStackOfPackagesTests.Packages.Where((data, index) => index % DegreeOfParallelism == 2);

        [Theory]
        [MemberData(nameof(Packages))]
        public async Task CheckTheSupportTypeOfAWholeStackOfPackages(string id, string version, SupportType expectedSupportType)
        {
            var package = await GetPackageAsync(id, version);
            package.SupportType.Should().Be(expectedSupportType);
        }
    }

    [SuppressMessage("ReSharper", "VSTHRD200")]
    public class WholeStackOfPackagesTests4 : WholeStackOfPackagesTests
    {
        public new static IEnumerable<object[]> Packages = WholeStackOfPackagesTests.Packages.Where((data, index) => index % DegreeOfParallelism == 3);

        [Theory]
        [MemberData(nameof(Packages))]
        public async Task CheckTheSupportTypeOfAWholeStackOfPackages(string id, string version, SupportType expectedSupportType)
        {
            var package = await GetPackageAsync(id, version);
            package.SupportType.Should().Be(expectedSupportType);
        }
    }
}